#ifndef MARPAESLIF_JSONTESTERSTRICTEXTERNAL_H
#define MARPAESLIF_JSONTESTERSTRICTEXTERNAL_H

static const char *grammars =
  "# --------------------------------------------------\n"
  "# Meta settings\n"
  "# --------------------------------------------------\n"
  ":desc              ::= 'Strict JSON Grammar'\n"
  ":default           ::= action => ::shift fallback-encoding => UTF-8 discard-is-fallback => 1\n"
  "\n"
  "# -----------------------------------------------------------------------------------------------------------\n"
  "# In JSON grammar, all matches are exclusive, giving priority to symbols is way skip unnecessary match trials\n"
  "# -----------------------------------------------------------------------------------------------------------\n"
  ":symbol ::= ','                                                     name => COMMA\n"
  ":symbol ::= '{'                                                     name => LBRACKET\n"
  ":symbol ::= '}'                                                     name => RBRACKET\n"
  ":symbol ::= '['                                                     name => LSQUARE\n"
  ":symbol ::= ']'                                                     name => RSQUARE\n"
  ":symbol ::= 'true'                                                  name => TRUE\n"
  ":symbol ::= 'false'                                                 name => FALSE\n"
  ":symbol ::= 'null'                                                  name => NULL\n"
  ":symbol ::= '\"'                                                    name => DQUOTE\n"
  ":symbol ::= [0-9-]                                                  name => NUMBER_LOOKAHEAD\n"
  ":symbol ::= /-?(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/ name => NUMBER\n"
  "#\n"
  "# A string containing only unescaped characters is considered more probable than one having escapes\n"
  "#\n"
  "\n"
  ":symbol ::= /[^\"\\\\\\x00-\\x1F]+/u                                name => UNESCAPED_CHARACTERS priority => -1\n"
  ":symbol ::= /(?:\\\\[\"\\\\\\/bfnrt])+/u                            name => ESCAPED_CHARACTERS   priority => -1\n"
  ":symbol ::= /(?:\\\\u[[:xdigit:]]{4})+/u                            name => ESCAPED_UNICODE      priority => -1\n"
  "\n"
  "# ---------------------------------\n"
  "# Discard unsignificant whitespaces\n"
  "# ---------------------------------\n"
  ":discard           ::= /[\\x{9}\\x{A}\\x{D}\\x{20}]+/\n"
  "\n"
  "#\n"
  "# -------------\n"
  "# Symbol events\n"
  "# ------------\n"
  ":symbol ::= $DQUOTE           pause => after event => :discard[switch]\n"
  ":symbol ::= $NUMBER_LOOKAHEAD pause => after event => :discard[off]\n"
  ":symbol ::= $NUMBER           pause => after event => :discard[on]\n"
  "\n"
  "# ----------\n"
  "# JSON value\n"
  "# ----------\n"
  "value               ::= object\n"
  "                      | array\n"
  "                      | string\n"
  "                      | constant\n"
  "                      | number\n"
  "\n"
  "# -----------\n"
  "# JSON object\n"
  "# -----------\n"
  "object              ::= $LBRACKET members $RBRACKET  action         => ::copy[1]\n"
  "                      | $LBRACKET         $RBRACKET  action         => ::lua->object_empty\n"
  "members             ::= member+                      action         => ::lua->object\n"
  "                                                     separator      => $COMMA\n"
  "                                                     proper         => 1\n"
  "                                                     hide-separator => 1\n"
  "member              ::= string (-':'-) value         action         => ::row\n"
  "\n"
  "# ----------\n"
  "# JSON Array\n"
  "# ----------\n"
  "array               ::= $LSQUARE elements $RSQUARE   action         => ::copy[1]\n"
  "elements            ::= value*                       action         => ::row\n"
  "                                                     separator      => $COMMA\n"
  "                                                     proper         => 1\n"
  "                                                     hide-separator => 1\n"
  "\n"
  "# -----------\n"
  "# JSON String\n"
  "# -----------\n"
  "\n"
  "string              ::= $DQUOTE string_parts $DQUOTE action         => ::copy[1]\n"
  "                      | $DQUOTE              $DQUOTE action         => ::u8\"\" # Empty string\n"
  "string_parts        ::= string_part+                 action         => ::concat\n"
  "string_part         ::= $UNESCAPED_CHARACTERS\n"
  "                      | $ESCAPED_CHARACTERS          action         => ::lua->string_escape_part\n"
  "                      | $ESCAPED_UNICODE             action         => ::lua->string_unicode_part\n"
  "\n"
  "\n"
  "# -------------\n"
  "# JSON constant\n"
  "# -------------\n"
  "constant ::= $TRUE                                   action         => ::true\n"
  "           | $FALSE                                  action         => ::false\n"
  "           | $NULL                                   action         => ::undef\n"
  "\n"
  "# -----------\n"
  "# JSON number\n"
  "# -----------\n"
  "number         ::= (?=$NUMBER_LOOKAHEAD) $NUMBER     action => ::luac->function(lookahead,number) return tonumber(number) end\n"
  "\n"
  "<luascript>\n"
  "function object_empty()\n"
  "  return {}\n"
  "end\n"
  "\n"
  "function object(...)\n"
  "  local output = niledtablekv()\n"
  "  for n=1,select('#',...) do\n"
  "    local member = select(n, ...)\n"
  "    output[member[1]] = member[2]\n"
  "  end\n"
  "  return output\n"
  "end\n"
  "\n"
  "function only_unescaped_characters(input)\n"
  "  local output = input:sub(2, -2)\n"
  "  output:encoding('UTF-8')\n"
  "  return output\n"
  "end"
  "\n"
  "function string_escape_part(input)\n"
  "  local c = input:sub(2, 2) -- get second character\n"
  "  if     c == '\"'  then return c\n"
  "  elseif c == '\\\\' then return c\n"
  "  elseif c == '/'  then return c\n"
  "  elseif c == 'b'  then return '\\b'\n"
  "  elseif c == 'f'  then return '\\f'\n"
  "  elseif c == 'n'  then return '\\n'\n"
  "  elseif c == 'r'  then return '\\r'\n"
  "  elseif c == 't'  then return '\\t'\n"
  "  else   error('Unsupported escaped character '..c)\n"
  "  end\n"
  "end\n"
  "\n"
  "function string_unicode_part(input)\n"
  "  local stringtable = {}\n"
  "  local uint32 = {}\n"
  "  local p = 1\n"
  "  local pmax = input:len()\n"
  "  while p <= pmax do\n"
  "    local u = input:sub(p+2, p + 5)\n"
  "    uint32[#uint32+1] = tonumber('0x'..u)\n"
  "    p = p + 6\n"
  "  end\n"
  "  local j = 2\n"
  "  for i = 1, #uint32 do\n"
  "    local u = uint32[i]\n"
  "    if ((j <= #uint32) and (u >= 0xD800) and (u <= 0xDBFF) and (uint32[j] >= 0xDC00) and (uint32[j] <= 0xDFFF)) then\n"
  "      -- Surrogate UTF-16 pair\n"
  "      u = 0x10000 + ((u & 0x3FF) << 10) + (uint32[j] & 0x3FF)\n"
  "      i = i + 1\n"
  "      j = j + 1\n"
  "    end\n"
  "    if ((u >= 0xD800) and (u <= 0xDFFF)) then\n"
  "      u = 0xFFFD -- Replacement character\n"
  "    end\n"
  "    stringtable[#stringtable + 1] = utf8.char(u)\n"
  "  end\n"
  "  return table.concat(stringtable)\n"
  "end\n"
  "</luascript>\n"
  ;

#endif /* MARPAESLIF_JSONTESTERSTRICTEXTERNAL_H */
