=encoding UTF-8

=head1 NAME

marpaESLIF_PROPOSITIONALLOGIC - Extended Marpa's Scanless Interface Propositional Logic Tutorial

=head1 DESCRIPTION

marpaESLIF is a Scanless Interface expressed in a BNF format, that is using L<marpaWrapper|https://github.com/jddurand/c-marpaWrapper>, itself being a thin interface on top of L<libmarpa|https://jeffreykegler.github.io/Marpa-web-site/libmarpa.html> parser.

This documentation is giving a tutorial using propositional logic and an external lexer. We will make a binary that is evaluating the sentence as the input goes on.

=head2 GRAMMAR

The BNF for propositional logic is:

    :default ::= action => ::shift

    Sentence        ::= TRUE
                      | FALSE
                      | SYMBOL
                      | LPAREN Sentence RPAREN              assoc => group action => ::copy[1]
                     || NOT Sentence                                       action => action_not
                     ||        Sentence        AND Sentence                action => action_and
                     ||        Sentence         OR Sentence                action => action_or
                     ||        Sentence    IMPLIES Sentence                action => action_implies
                      |        Sentence EQUIVALENT Sentence                action => action_equivalent

    _DUMMY      ~ [^\s\S]
    TRUE        ~ _DUMMY
    FALSE       ~ _DUMMY
    LPAREN      ~ _DUMMY
    RPAREN      ~ _DUMMY
    NOT         ~ _DUMMY
    AND         ~ _DUMMY
    OR          ~ _DUMMY
    IMPLIES     ~ _DUMMY
    EQUIVALENT  ~ _DUMMY
    SYMBOL      ~ _DUMMY
