#ifndef MARPAESLIF_INTERNAL_ESLIF_H
#define MARPAESLIF_INTERNAL_ESLIF_H

#define G1_RULE_STATEMENTS                       "G1_rule_statements"
#define G1_RULE_STATEMENT_01                     "G1_rule_statement_01"
#define G1_RULE_STATEMENT_02                     "G1_rule_statement_02"
#define G1_RULE_STATEMENT_03                     "G1_rule_statement_03"
#define G1_RULE_STATEMENT_04                     "G1_rule_statement_04"
#define G1_RULE_STATEMENT_05                     "G1_rule_statement_05"
#define G1_RULE_STATEMENT_06                     "G1_rule_statement_06"
#define G1_RULE_STATEMENT_07                     "G1_rule_statement_07"
#define G1_RULE_STATEMENT_08                     "G1_rule_statement_08"
#define G1_RULE_STATEMENT_09                     "G1_rule_statement_09"
#define G1_RULE_STATEMENT_10                     "G1_rule_statement_10"
#define G1_RULE_STATEMENT_11                     "G1_rule_statement_11"
#define G1_RULE_STATEMENT_12                     "G1_rule_statement_12"
#define G1_RULE_STATEMENT_13                     "G1_rule_statement_13"
#define G1_RULE_STATEMENT_14                     "G1_rule_statement_14"
#define G1_RULE_STATEMENT_15                     "G1_rule_statement_15"
#define G1_RULE_STATEMENT_16                     "G1_rule_statement_16"
#define G1_RULE_STATEMENT_17                     "G1_rule_statement_17"
#define G1_RULE_START_RULE                       "G1_rule_start_rule"
#define G1_RULE_DESC_RULE                        "G1_rule_desc_rule"
#define G1_RULE_EMPTY_RULE                       "G1_rule_empty_rule"
#define G1_RULE_NULL_STATEMENT                   "G1_rule_null_statement"
#define G1_RULE_STATEMENT_GROUP                  "G1_rule_statement_group"
#define G1_RULE_PRIORITY_RULE                    "G1_rule_priority_rule"
#define G1_RULE_QUANTIFIED_RULE                  "G1_rule_quantified_rule"
#define G1_RULE_DISCARD_RULE                     "G1_rule_discard_rule"
#define G1_RULE_DEFAULT_RULE                     "G1_rule_default_rule"
#define G1_RULE_LEXEME_DEFAULT_STATEMENT_1       "G1_rule_lexeme_default_statement_1"
#define G1_RULE_LEXEME_DEFAULT_STATEMENT_2       "G1_rule_lexeme_default_statement_2"
#define G1_RULE_DISCARD_DEFAULT_STATEMENT_1      "G1_rule_discard_default_statement_1"
#define G1_RULE_DISCARD_DEFAULT_STATEMENT_2      "G1_rule_discard_default_statement_2"
#define G1_RULE_LEXEME_RULE                      "G1_rule_lexeme_rule"
#define G1_RULE_COMPLETION_EVENT_DECLARATION_1   "G1_rule_completion_event_declaration_1"
#define G1_RULE_COMPLETION_EVENT_DECLARATION_2   "G1_rule_completion_event_declaration_2"
#define G1_RULE_NULLED_EVENT_DECLARATION_1       "G1_rule_nulled_event_declaration_1"
#define G1_RULE_NULLED_EVENT_DECLARATION_2       "G1_rule_nulled_event_declaration_2"
#define G1_RULE_NULLED_PREDICTED_DECLARATION_1   "G1_rule_nulled_predicted_declaration_1"
#define G1_RULE_NULLED_PREDICTED_DECLARATION_2   "G1_rule_nulled_predicted_declaration_2"
#define G1_RULE_INACCESSIBLE_STATEMENT           "G1_rule_inaccessible_statement"
#define G1_RULE_INACCESSIBLE_TREATMENT_1         "G1_rule_inaccessible_treatment_1"
#define G1_RULE_INACCESSIBLE_TREATMENT_2         "G1_rule_inaccessible_treatment_2"
#define G1_RULE_INACCESSIBLE_TREATMENT_3         "G1_rule_inaccessible_treatment_3"
#define G1_RULE_EXCEPTION_STATEMENT              "G1_rule_exception_statement"
#define G1_RULE_OP_DECLARE_1                     "G1_rule_op_declare_1"
#define G1_RULE_OP_DECLARE_2                     "G1_rule_op_declare_2"
#define G1_RULE_OP_DECLARE_3                     "G1_rule_op_declare_3"
#define G1_RULE_PRIORITIES                       "G1_rule_priorities"
#define G1_RULE_ALTERNATIVES                     "G1_rule_alternatives"
#define G1_RULE_ALTERNATIVE                      "G1_rule_alternative"
#define G1_RULE_ADVERB_LIST                      "G1_rule_adverb_list"
#define G1_RULE_ADVERB_LIST_ITEMS                "G1_rule_adverb_list_items"
#define G1_RULE_ADVERB_ITEM_01                   "G1_rule_adverb_item_01"
#define G1_RULE_ADVERB_ITEM_02                   "G1_rule_adverb_item_02"
#define G1_RULE_ADVERB_ITEM_03                   "G1_rule_adverb_item_03"
#define G1_RULE_ADVERB_ITEM_04                   "G1_rule_adverb_item_04"
#define G1_RULE_ADVERB_ITEM_05                   "G1_rule_adverb_item_05"
#define G1_RULE_ADVERB_ITEM_06                   "G1_rule_adverb_item_06"
#define G1_RULE_ADVERB_ITEM_07                   "G1_rule_adverb_item_07"
#define G1_RULE_ADVERB_ITEM_08                   "G1_rule_adverb_item_08"
#define G1_RULE_ADVERB_ITEM_09                   "G1_rule_adverb_item_09"
#define G1_RULE_ADVERB_ITEM_10                   "G1_rule_adverb_item_10"
#define G1_RULE_ADVERB_ITEM_11                   "G1_rule_adverb_item_11"
#define G1_RULE_ADVERB_ITEM_12                   "G1_rule_adverb_item_12"
#define G1_RULE_ADVERB_ITEM_13                   "G1_rule_adverb_item_13"
#define G1_RULE_ADVERB_ITEM_14                   "G1_rule_adverb_item_14"
#define G1_RULE_ACTION                           "G1_rule_action"
#define G1_RULE_AUTORANK                         "G1_rule_autorank"
#define G1_RULE_LEFT_ASSOCIATION                 "G1_rule_left_association"
#define G1_RULE_RIGHT_ASSOCIATION                "G1_rule_right_association"
#define G1_RULE_GROUP_ASSOCIATION                "G1_rule_group_association"
#define G1_RULE_SEPARATOR_ASSOCIATION            "G1_rule_separator_association"
#define G1_RULE_PROPER_ASSOCIATION               "G1_rule_proper_association"
#define G1_RULE_RANK_SPECIFICATION               "G1_rule_rank_specification"
#define G1_RULE_NULL_RANKING_SPECIFICATION_1     "G1_rule_null_ranking_specification_1"
#define G1_RULE_NULL_RANKING_SPECIFICATION_2     "G1_rule_null_ranking_specification_2"
#define G1_RULE_NULL_RANKING_CONSTANT_1          "G1_rule_null_ranking_constant_1"
#define G1_RULE_NULL_RANKING_CONSTANT_2          "G1_rule_null_ranking_constant_2"
#define G1_RULE_PRIORITY_SPECIFICATION           "G1_rule_priority_specification"
#define G1_RULE_PAUSE_SPECIFICATION              "G1_rule_pause_specification"
#define G1_RULE_EVENT_SPECIFICATION              "G1_rule_event_specification"
#define G1_RULE_EVENT_INITIALIZATION             "G1_rule_event_initialization"
#define G1_RULE_EVENT_INITIALIZER_1              "G1_rule_event_initializer_1"
#define G1_RULE_ON_OR_OFF_1                      "G1_rule_on_or_off_1"
#define G1_RULE_ON_OR_OFF_2                      "G1_rule_on_or_off_2"
#define G1_RULE_EVENT_INITIALIZER_2              "G1_rule_event_initializer_2"
#define G1_RULE_LATM_SPECIFICATION_1             "G1_rule_latm_specification_1"
#define G1_RULE_LATM_SPECIFICATION_2             "G1_rule_latm_specification_2"
#define G1_RULE_NAMING                           "G1_rule_naming"
#define G1_RULE_NULL_ADVERB                      "G1_rule_null_adverb"
#define G1_RULE_ALTERNATIVE_NAME_1               "G1_rule_alternative_name_1"
#define G1_RULE_ALTERNATIVE_NAME_2               "G1_rule_alternative_name_2"
#define G1_RULE_EVENT_NAME_1                     "G1_rule_event_name_1"
#define G1_RULE_EVENT_NAME_2                     "G1_rule_event_name_2"
#define G1_RULE_LHS                              "G1_rule_lhs"
#define G1_RULE_RHS                              "G1_rule_rhs"
#define G1_RULE_RHS_PRIMARY_1                    "G1_rule_rhs_primary_1"
#define G1_RULE_RHS_PRIMARY_2                    "G1_rule_rhs_primary_2"
#define G1_RULE_RHS_PRIMARY_LIST                 "G1_rule_rhs_primary_list"
#define G1_RULE_PARENTHESIZED_RHS_EXCEPTION_LIST "G1_rule_parenthesized_rhs_exception_list"
#define G1_RULE_RHS_EXCEPTION_LIST               "G1_rule_rhs_exception_list"
#define G1_RULE_RHS_EXCEPTION_1                  "G1_rule_rhs_exception_1"
#define G1_RULE_RHS_EXCEPTION_2                  "G1_rule_rhs_exception_2"
#define G1_RULE_RHS_EXCEPTION_3                  "G1_rule_rhs_exception_3"
#define G1_RULE_SINGLE_SYMBOL_1                  "G1_rule_single_symbol_1"
#define G1_RULE_SINGLE_SYMBOL_2                  "G1_rule_single_symbol_2"
#define G1_RULE_SINGLE_SYMBOL_3                  "G1_rule_single_symbol_3"
#define G1_RULE_SYMBOL                           "G1_rule_symbol"
#define G1_RULE_SYMBOL_NAME_1                    "G1_rule_symbol_name_1"
#define G1_RULE_SYMBOL_NAME_2                    "G1_rule_symbol_name_2"
#define G1_RULE_ACTION_NAME_1                    "G1_rule_action_name_1"
#define G1_RULE_ACTION_NAME_2                    "G1_rule_action_name_2"
#define G1_RULE_ACTION_NAME_3                    "G1_rule_action_name_3"
#define G1_RULE_QUANTIFIER_1                     "G1_rule_quantifier_1"
#define G1_RULE_QUANTIFIER_2                     "G1_rule_quantifier_2"
#define G1_RULE_DISCARD_1                        "G1_rule_discard_1"
#define G1_RULE_DISCARD_2                        "G1_rule_discard_2"
#define G1_RULE_DISCARD_3                        "G1_rule_discard_3"

#define G1_ACTION_STATEMENTS                       "G1_action_statements"
#define G1_ACTION_STATEMENT_01                     "G1_action_statement_01"
#define G1_ACTION_STATEMENT_02                     "G1_action_statement_02"
#define G1_ACTION_STATEMENT_03                     "G1_action_statement_03"
#define G1_ACTION_STATEMENT_04                     "G1_action_statement_04"
#define G1_ACTION_STATEMENT_05                     "G1_action_statement_05"
#define G1_ACTION_STATEMENT_06                     "G1_action_statement_06"
#define G1_ACTION_STATEMENT_07                     "G1_action_statement_07"
#define G1_ACTION_STATEMENT_08                     "G1_action_statement_08"
#define G1_ACTION_STATEMENT_09                     "G1_action_statement_09"
#define G1_ACTION_STATEMENT_10                     "G1_action_statement_10"
#define G1_ACTION_STATEMENT_11                     "G1_action_statement_11"
#define G1_ACTION_STATEMENT_12                     "G1_action_statement_12"
#define G1_ACTION_STATEMENT_13                     "G1_action_statement_13"
#define G1_ACTION_STATEMENT_14                     "G1_action_statement_14"
#define G1_ACTION_STATEMENT_15                     "G1_action_statement_15"
#define G1_ACTION_STATEMENT_16                     "G1_action_statement_16"
#define G1_ACTION_STATEMENT_17                     "G1_action_statement_17"
#define G1_ACTION_START_RULE                       "G1_action_start_rule"
#define G1_ACTION_DESC_RULE                        "G1_action_desc_rule"
#define G1_ACTION_EMPTY_RULE                       "G1_action_empty_rule"
#define G1_ACTION_NULL_STATEMENT                   "G1_action_null_statement"
#define G1_ACTION_STATEMENT_GROUP                  "G1_action_statement_group"
#define G1_ACTION_PRIORITY_RULE                    "G1_action_priority_rule"
#define G1_ACTION_QUANTIFIED_RULE                  "G1_action_quantified_rule"
#define G1_ACTION_DISCARD_RULE                     "G1_action_discard_rule"
#define G1_ACTION_DEFAULT_RULE                     "G1_action_default_rule"
#define G1_ACTION_LEXEME_DEFAULT_STATEMENT_1       "G1_action_lexeme_default_statement_1"
#define G1_ACTION_LEXEME_DEFAULT_STATEMENT_2       "G1_action_lexeme_default_statement_2"
#define G1_ACTION_DISCARD_DEFAULT_STATEMENT_1      "G1_action_discard_default_statement_1"
#define G1_ACTION_DISCARD_DEFAULT_STATEMENT_2      "G1_action_discard_default_statement_2"
#define G1_ACTION_LEXEME_RULE                      "G1_action_lexeme_rule"
#define G1_ACTION_COMPLETION_EVENT_DECLARATION_1   "G1_action_completion_event_declaration_1"
#define G1_ACTION_COMPLETION_EVENT_DECLARATION_2   "G1_action_completion_event_declaration_2"
#define G1_ACTION_NULLED_EVENT_DECLARATION_1       "G1_action_nulled_event_declaration_1"
#define G1_ACTION_NULLED_EVENT_DECLARATION_2       "G1_action_nulled_event_declaration_2"
#define G1_ACTION_NULLED_PREDICTED_DECLARATION_1   "G1_action_nulled_predicted_declaration_1"
#define G1_ACTION_NULLED_PREDICTED_DECLARATION_2   "G1_action_nulled_predicted_declaration_2"
#define G1_ACTION_INACCESSIBLE_STATEMENT           "G1_action_inaccessible_statement"
#define G1_ACTION_INACCESSIBLE_TREATMENT_1         "G1_action_inaccessible_treatment_1"
#define G1_ACTION_INACCESSIBLE_TREATMENT_2         "G1_action_inaccessible_treatment_2"
#define G1_ACTION_INACCESSIBLE_TREATMENT_3         "G1_action_inaccessible_treatment_3"
#define G1_ACTION_EXCEPTION_STATEMENT              "G1_action_exception_statement"
#define G1_ACTION_OP_DECLARE_1                     "G1_action_op_declare_1"
#define G1_ACTION_OP_DECLARE_2                     "G1_action_op_declare_2"
#define G1_ACTION_OP_DECLARE_3                     "G1_action_op_declare_3"
#define G1_ACTION_PRIORITIES                       "G1_action_priorities"
#define G1_ACTION_ALTERNATIVES                     "G1_action_alternatives"
#define G1_ACTION_ALTERNATIVE                      "G1_action_alternative"
#define G1_ACTION_ADVERB_LIST                      "G1_action_adverb_list"
#define G1_ACTION_ADVERB_LIST_ITEMS                "G1_action_adverb_list_items"
#define G1_ACTION_ADVERB_ITEM_01                   "::shift"
#define G1_ACTION_ADVERB_ITEM_02                   "::shift"
#define G1_ACTION_ADVERB_ITEM_03                   "::shift"
#define G1_ACTION_ADVERB_ITEM_04                   "::shift"
#define G1_ACTION_ADVERB_ITEM_05                   "::shift"
#define G1_ACTION_ADVERB_ITEM_06                   "::shift"
#define G1_ACTION_ADVERB_ITEM_07                   "::shift"
#define G1_ACTION_ADVERB_ITEM_08                   "::shift"
#define G1_ACTION_ADVERB_ITEM_09                   "::shift"
#define G1_ACTION_ADVERB_ITEM_10                   "::shift"
#define G1_ACTION_ADVERB_ITEM_11                   "::shift"
#define G1_ACTION_ADVERB_ITEM_12                   "::shift"
#define G1_ACTION_ADVERB_ITEM_13                   "::shift"
#define G1_ACTION_ADVERB_ITEM_14                   "::shift"
#define G1_ACTION_ACTION                           "G1_action_action"
#define G1_ACTION_AUTORANK                         "G1_action_autorank"
#define G1_ACTION_LEFT_ASSOCIATION                 "G1_action_left_association"
#define G1_ACTION_RIGHT_ASSOCIATION                "G1_action_right_association"
#define G1_ACTION_GROUP_ASSOCIATION                "G1_action_group_association"
#define G1_ACTION_SEPARATOR_ASSOCIATION            "G1_action_separator_association"
#define G1_ACTION_PROPER_ASSOCIATION               "G1_action_proper_association"
#define G1_ACTION_RANK_SPECIFICATION               "G1_action_rank_specification"
#define G1_ACTION_NULL_RANKING_SPECIFICATION_1     "G1_action_null_ranking_specification_1"
#define G1_ACTION_NULL_RANKING_SPECIFICATION_2     "G1_action_null_ranking_specification_2"
#define G1_ACTION_NULL_RANKING_CONSTANT_1          "G1_action_null_ranking_constant_1"
#define G1_ACTION_NULL_RANKING_CONSTANT_2          "G1_action_null_ranking_constant_2"
#define G1_ACTION_PRIORITY_SPECIFICATION           "G1_action_priority_specification"
#define G1_ACTION_PAUSE_SPECIFICATION              "G1_action_pause_specification"
#define G1_ACTION_EVENT_SPECIFICATION              "G1_action_event_specification"
#define G1_ACTION_EVENT_INITIALIZATION             "G1_action_event_initialization"
#define G1_ACTION_EVENT_INITIALIZER_1              "G1_action_event_initializer_1"
#define G1_ACTION_ON_OR_OFF_1                      "G1_action_on_or_off_1"
#define G1_ACTION_ON_OR_OFF_2                      "G1_action_on_or_off_2"
#define G1_ACTION_EVENT_INITIALIZER_2              "G1_action_event_initializer_2"
#define G1_ACTION_LATM_SPECIFICATION_1             "G1_action_latm_specification_1"
#define G1_ACTION_LATM_SPECIFICATION_2             "G1_action_latm_specification_2"
#define G1_ACTION_NAMING                           "G1_action_naming"
#define G1_ACTION_NULL_ADVERB                      "G1_action_null_adverb"
#define G1_ACTION_ALTERNATIVE_NAME_1               "G1_action_alternative_name_1"
#define G1_ACTION_ALTERNATIVE_NAME_2               "G1_action_alternative_name_2"
#define G1_ACTION_EVENT_NAME_1                     "G1_action_event_name_1"
#define G1_ACTION_EVENT_NAME_2                     "G1_action_event_name_2"
#define G1_ACTION_LHS                              "::shift"
#define G1_ACTION_RHS                              "::shift"
#define G1_ACTION_RHS_PRIMARY_1                    "G1_action_rhs_primary_1"
#define G1_ACTION_RHS_PRIMARY_2                    "::shift"
#define G1_ACTION_RHS_PRIMARY_LIST                 "G1_action_rhs_primary_list"
#define G1_ACTION_PARENTHESIZED_RHS_EXCEPTION_LIST "G1_action_parenthesized_rhs_exception_list"
#define G1_ACTION_RHS_EXCEPTION_LIST               "G1_action_rhs_exception_list"
#define G1_ACTION_RHS_EXCEPTION_1                  "G1_action_rhs_exception_1"
#define G1_ACTION_RHS_EXCEPTION_2                  "G1_action_rhs_exception_2"
#define G1_ACTION_RHS_EXCEPTION_3                  "G1_action_rhs_exception_3"
#define G1_ACTION_SINGLE_SYMBOL_1                  "G1_action_single_symbol_1"
#define G1_ACTION_SINGLE_SYMBOL_2                  "G1_action_single_symbol_2"
#define G1_ACTION_SINGLE_SYMBOL_3                  "G1_action_single_symbol_3"
#define G1_ACTION_SYMBOL                           "G1_action_symbol"
#define G1_ACTION_SYMBOL_NAME_1                    "G1_action_symbol_name_1"
#define G1_ACTION_SYMBOL_NAME_2                    "::shift"
#define G1_ACTION_ACTION_NAME_1                    "::shift"
#define G1_ACTION_ACTION_NAME_2                    "::shift"
#define G1_ACTION_ACTION_NAME_3                    "::shift"
#define G1_ACTION_QUANTIFIER_1                     "G1_action_quantifier_1"
#define G1_ACTION_QUANTIFIER_2                     "G1_action_quantifier_2"
#define G1_ACTION_DISCARD_1                        "G1_action_discard_1"
#define G1_ACTION_DISCARD_2                        "G1_action_discard_2"
#define G1_ACTION_DISCARD_3                        "G1_action_discard_3"

typedef struct bootstrap_grammar_terminal {
  int                        idi;                 /* Identifier */
  marpaESLIF_terminal_type_t terminalType;        /* Terminal type */
  marpaESLIF_uint32_t        optioni;             /* Terminal option */
  char                      *utf8s;               /* ASCII UTF-8 compatible encoding */
  char                      *testFullMatchs;
  char                      *testPartialMatchs;
} bootstrap_grammar_terminal_t;

typedef struct bootstrap_grammar_meta {
  int    idi;                  /* Identifier */
  char  *descs;                /* Description */
  short  startb;               /* Start symbol ? */
  short  discardb;             /* Discard symbol ? */
  char  *defaultSymbolactions; /* Default symbol action */
  char  *defaultRuleactions;   /* Default rule action */
} bootstrap_grammar_meta_t;

typedef enum bootstrap_grammar_rule_type {
  MARPAESLIF_RULE_TYPE_ALTERNATIVE,
  MARPAESLIF_RULE_TYPE_SEQUENCE
} bootstrap_grammar_rule_type_t;

typedef struct bootstrap_grammar_rule {
  int                           lhsi;
  char                         *descs;
  bootstrap_grammar_rule_type_t type;
  size_t                        nrhsl;
  int                           rhsip[10];  /* 10 is arbitrary - just to make C happy */
  int                           minimumi;
  int                           separatori;
  short                         properb;
  char                         *actions;
} bootstrap_grammar_rule_t;

#include "marpaESLIF/internal/eslif/L0.h"
#include "marpaESLIF/internal/eslif/G1.h"

#endif /* MARPAESLIF_INTERNAL_ESLIF_H */
