static const char *MARPAESLIFLUA_MARPAESLIFJSON =
  "\n"
  "-- marpaESLIFJSON.lua\n"
  "-- The intention is NOT to provide a true proxy class that hides its members\n"
  "-- This is just a handy class over marpaESLIFJSONEncoder and marpaESLIFJSONDecoder\n"
  "-- C.f. https://stackoverflow.com/questions/4799078/how-can-one-implement-oo-in-lua\n"
  "--\n"
  "-- C.f. https://stackoverflow.com/questions/4799078/how-can-one-implement-oo-in-lua\n"
  "--\n"
  "\n"
  "class = {} -- Will remain empty as class\n"
  "mt = {} -- Will contain everything the instances will contain _by default_\n"
  "\n"
  "mt.new = function(self,marpaESLIFp,strict)\n"
  "   local inst = {\n"
  "      _marpaESLIFJSONEncoder = marpaESLIFp:marpaESLIFJSONEncoder_new(strict),\n"
  "      _marpaESLIFJSONDecoder = marpaESLIFp:marpaESLIFJSONDecoder_new(strict)\n"
  "   }\n"
  "   return setmetatable(inst,getmetatable(class))\n"
  "end\n"
  "\n"
  "mt.encode = function(self, value)\n"
  "   return self._marpaESLIFJSONEncoder:encode(value)\n"
  "end\n"
  "\n"
  "mt.decode = function(self, value)\n"
  "   return self._marpaESLIFJSONDecoder:decode(value)\n"
  "end\n"
  "\n"
  "mt.__index = mt -- Look up all inexistent indices in the metatable\n"
  "\n"
  "setmetatable(class,mt)\n"
  "\n"
  "return class\n"
  "\n";
