=encoding UTF-8

=head1 NAME

marpaESLIF_TUTORIAL - Extended Marpa's Scanless Interface Tutorial

=head1 DESCRIPTION

marpaESLIF is a Scanless Interface expressed in a BNF format, that is using L<marpaWrapper|https://github.com/jddurand/c-marpaWrapper>, itself being a thin interface on top of L<libmarpa|https://jeffreykegler.github.io/Marpa-web-site/libmarpa.html> parser.

This documentation is giving tutorials, in increasing order of complexity:

=over

=item Calculator

C.f. L<marpaESLIF Calculator|https://github.com/jddurand/c-marpaESLIF/tree/master/doc/Tutorial/Calculator>

=item Propositional Logic

C.f. L<marpaESLIF Propositional Logic|https://github.com/jddurand/c-marpaESLIF/tree/master/doc/Tutorial/propositionalLogic>

=back

=head1 SEE ALSO

L<marpaESLIF|https://github.com/jddurand/c-marpaESLIF>
