package org.parser.marpa;

/**
 * ESLIFException represent exception generated by the marpaESLIF layer.
 * <p>
 * Only the JNI layer, a C code that is interfacing Java to marpaESLIF can generate this exception.
 */
@SuppressWarnings("serial")
public class ESLIFException extends Exception {

	/**
	 * 
	 * @param message the message describing the exception
	 */
	public ESLIFException(String message) {
		super(message);
	}
}
