static const char *marpaESLIFJSON_decode_extended_grammars =
  "                   #######################################################\n"
  "                   # >>>>>>>>>>>>>>> Extended JSON Grammar <<<<<<<<<<<<<<<\n"
  "                   #######################################################\n"
  "\n"
  "# --------------------------------------------------\n"
  "# Meta settings\n"
  "# --------------------------------------------------\n"
  ":desc              ::= 'Extended JSON Grammar'\n"
  ":default           ::= event-action => marpaESLIFJsonEventAction fallback-encoding => UTF-8\n"
  "\n"
  "# -----------------------------------------------------------\n"
  "# Discard unsignificant whitespaces, Perl comment C++ comment\n"
  "# -----------------------------------------------------------\n"
  ":discard           ::= /[\\x{9}\\x{A}\\x{D}\\x{20}]+|#[^\\n]*|\\/\\/[^\\n]*|\\/\\*(?:(?:[^\\*]+|\\*(?!\\/))*)\\*\\//u\n"
  "\n"
  "# ----------------\n"
  "# Start is a value\n"
  "# ----------------\n"
  ":start             ::= value\n"
  "\n"
  "# ------\n"
  "# Events\n"
  "# ------\n"
  ":terminal ::= '['                                                                                                           pause => after  event => 0_inc$\n"
  ":terminal ::= ']'                                                                                                           pause => after  event => 1_dec$\n"
  ":terminal ::= '{'                                                                                                           pause => after  event => 0_inc$\n"
  ":terminal ::= '}'                                                                                                           pause => after  event => 1_dec$\n"
  ":terminal ::= /(?:[^\"\\\\]+)|(?:\\\\[\"\\\\\\/bfnrt])|(?:(?:\\\\u[[:xdigit:]]{4})+)/                                       pause => after  event => 2_CHAR$ name => CHAR\n"
  ":terminal ::= /true|false|null|(?:(?:[+-]?(?:[0-9]+)(?:\\.[0-9]+)?(?:E[+-]?[0-9]+)?)|(?:[+-]?Inf(?:inity)?)|(?:[+-]?NaN))/i pause => after  event => 3_CONSTANT_OR_NUMBER$ name => CONSTANT_OR_NUMBER\n"
  ":terminal ::= '\"'                                                                                                          pause => after  event => 4_dquote$\n"
  "\n"
  "# ----------\n"
  "# JSON value\n"
  "# ----------\n"
  "value              ::= string\n"
  "                     | object\n"
  "                     | array\n"
  "                     | constant_or_number\n"
  "\n"
  "# -----------\n"
  "# JSON String\n"
  "# -----------\n"
  "string             ::= '\"' chars '\"'\n"
  "chars              ::= char*\n"
  "char               ::= /(?:[^\"\\\\]+)|(?:\\\\[\"\\\\\\/bfnrt])|(?:(?:\\\\u[[:xdigit:]]{4})+)/\n"
  "\n"
  "# -----------\n"
  "# JSON object\n"
  "# -----------\n"
  "object             ::= '{' members '}'\n"
  "members            ::= pair*              separator => commas proper => 0 # Multiple commas everywhere\n"
  "pair               ::= string ':' value\n"
  "\n"
  "# ----------\n"
  "# JSON Array\n"
  "# ----------\n"
  "array              ::= '[' elements ']'\n"
  "elements           ::= value*             separator => commas proper => 0 # Multiple commas everywhere\n"
  "\n"
  "# -----------------------\n"
  "# JSON constant or number\n"
  "# -----------------------\n"
  "constant_or_number ::= /true|false|null|(?:(?:[+-]?(?:[0-9]+)(?:\\.[0-9]+)?(?:E[+-]?[0-9]+)?)|(?:[+-]?Inf(?:inity)?)|(?:[+-]?NaN))/i\n"
  "\n"
  "# ---------\n"
  "# Separator\n"
  "# ---------\n"
  "comma              ::= ','\n"
  "commas             ::= comma+\n"
  ;
