static const char *marpaESLIFJSON_decode_strict_grammars =
  "                   #####################################################\n"
  "                   # >>>>>>>>>>>>>>> Strict JSON Grammar <<<<<<<<<<<<<<<\n"
  "                   #####################################################\n"
  "\n"
  "# --------------------------------------------------\n"
  "# Default action is to propagate the first RHS value\n"
  "# --------------------------------------------------\n"
  ":desc      ::= 'Strict JSON Grammar'\n"
  ":default   ::= event-action      => marpaESLIFJsonEventAction\n"
  "               fallback-encoding => UTF-8\n"
  "\n"
  "# ---------------------------------\n"
  "# Discard unsignificant whitespaces\n"
  "# ---------------------------------\n"
  ":discard ::= /[\\x{9}\\x{A}\\x{D}\\x{20}]+/\n"
  "\n"
  "# ----------------\n"
  "# Start is a value\n"
  "# ----------------\n"
  ":start     ::= value\n"
  "\n"
  "# ------\n"
  "# Events\n"
  "# ------\n"
  ":terminal  ::= '['          pause => after  event => 0_inc\n"
  ":terminal  ::= ']'          pause => after  event => 1_dec\n"
  ":terminal  ::= '{'          pause => after  event => 0_inc\n"
  ":terminal  ::= '}'          pause => after  event => 1_dec\n"
  "\n"
  ":lexeme    ::= CHAR         pause => after  event => 2_CHAR\n"
  ":lexeme    ::= CONSTANT     pause => after  event => 4_CONSTANT\n"
  ":lexeme    ::= DQUOTE_START pause => before event => 5_DQUOTE_START  # For string initialization + discard hook\n"
  ":lexeme    ::= DQUOTE_END   pause => before event => 6_DQUOTE_END    # For discard hook\n"
  ":lexeme    ::= NUMBER       pause => after  event => 7_NUMBER\n"
  "\n"
  "# ----------\n"
  "# JSON value\n"
  "# ----------\n"
  "value      ::= string\n"
  "             | number\n"
  "             | object\n"
  "             | array\n"
  "             | constant\n"
  "\n"
  "# -----------\n"
  "# JSON String\n"
  "# -----------\n"
  "string     ::= DQUOTE_START chars DQUOTE_END\n"
  "chars      ::= char*\n"
  "char       ::= CHAR\n"
  "\n"
  "# -----------\n"
  "# JSON Number\n"
  "# -----------\n"
  "number     ::= NUMBER\n"
  "\n"
  "# -----------\n"
  "# JSON object\n"
  "# -----------\n"
  "object     ::= '{' members '}'\n"
  "members    ::= pair*                        separator      => comma  # ... separated by comma(s)\n"
  "                                            proper         => 1      # ... with no trailing separator\n"
  "pair       ::= string ':' value\n"
  "\n"
  "# ----------\n"
  "# JSON Array\n"
  "# ----------\n"
  "array      ::= '[' elements ']'             \n"
  "elements   ::= value*                      separator      => comma   # ... separated by comma(s)\n"
  "                                           proper         => 1       # ... with no trailing separator\n"
  "\n"
  "# -------------\n"
  "# JSON constant\n"
  "# -------------\n"
  "constant   ::= CONSTANT\n"
  "\n"
  "# ---------\n"
  "# Separator\n"
  "# ---------\n"
  "comma      ::= ','\n"
  "\n"
  "# -------\n"
  "# Lexemes\n"
  "# -------\n"
  ":desc        ~ 'Strict JSON Grammar Lexemes'\n"
  ":default     ~ fallback-encoding => UTF-8\n"
  "CHAR         ~ /(?:[^\"\\\\\\x00-\\x1F]+)|(?:\\\\[\"\\\\\\/bfnrt])|(?:(?:\\\\u[[:xdigit:]]{4})+)/\n"
  "CONSTANT     ~ /true|false|null/\n"
  "DQUOTE_START ~ '\"'\n"
  "DQUOTE_END   ~ '\"'\n"
  "NUMBER       ~ /-?(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/\n"
  ;
