# - Try to find Iconv 
# Once done this will define 
# 
#  ICONV_FOUND - system has Iconv 
#  ICONV_INCLUDE_DIR - the Iconv include directory 
#  ICONV_LINK_FLAGS - Link these to use Iconv (list)
#  ICONV_LDFLAGS - Link these to use Iconv (string)
#  ICONV_SECOND_ARGUMENT_IS_CONST - the second argument for iconv() is const
# 
include(CheckCSourceCompiles)

IF (ICONV_INCLUDE_DIR AND ICONV_LIBRARIES)
  # Already in cache, be silent
  SET(ICONV_FIND_QUIETLY TRUE)
ENDIF (ICONV_INCLUDE_DIR AND ICONV_LIBRARIES)

FIND_PATH (_ICONV_INCLUDE_DIR iconv.h) 
 
FIND_LIBRARY (_ICONV_LIBRARIES NAMES iconv libiconv libiconv-2 c)
 
IF (_ICONV_INCLUDE_DIR AND _ICONV_LIBRARIES) 
   SET (_ICONV_FOUND TRUE) 
ENDIF (_ICONV_INCLUDE_DIR AND _ICONV_LIBRARIES) 

IF (_ICONV_FOUND)
  SET (CMAKE_REQUIRED_INCLUDES_PREVIOUS ${CMAKE_REQUIRED_INCLUDES})
  SET (CMAKE_REQUIRED_LIBRARIES_PREVIOUS ${CMAKE_REQUIRED_LIBRARIES})
  SET (CMAKE_REQUIRED_INCLUDES ${ICONV_INCLUDE_DIR})
  SET (CMAKE_REQUIRED_LIBRARIES ${ICONV_LIBRARIES})
  CHECK_C_SOURCE_COMPILES ("
  #include <iconv.h>
  int main(){
    iconv_t conv = 0;
    const char* in = 0;
    size_t ilen = 0;
    char* out = 0;
    size_t olen = 0;
    iconv(conv, &in, &ilen, &out, &olen);
    return 0;
  }
" ICONV_SECOND_ARGUMENT_IS_CONST )
  SET (CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES_PREVIOUS})
  SET (CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES_PREVIOUS})
ENDIF (_ICONV_FOUND)

IF (_ICONV_FOUND)
  SET (ICONV_FOUND TRUE)
  SET (ICONV_LIBRARIES ${_ICONV_LIBRARIES})
  SET (ICONV_INCLUDE_DIR ${_ICONV_INCLUDE_DIR})
  IF (NOT ICONV_FIND_QUIETLY) 
    MESSAGE (STATUS "Found Iconv: ${ICONV_LIBRARIES}") 
  ENDIF (NOT ICONV_FIND_QUIETLY) 
ELSE (_ICONV_FOUND) 
  IF (Iconv_FIND_REQUIRED) 
    MESSAGE (FATAL_ERROR "Could not find Iconv") 
  ENDIF (Iconv_FIND_REQUIRED) 
ENDIF(_ICONV_FOUND)

IF (_ICONV_FOUND) 
  IF (NOT _ICONV_LINK_FLAGS)
    SET (_ICONV_LINK_FLAGS ${ICONV_LIBRARIES})
  ENDIF ()
  SET (_ICONV_LDFLAGS " ")
  FOREACH (_iconv_link_flag ${_ICONV_LINK_FLAGS})
    SET (_ICONV_LDFLAGS "${_ICONV_LDFLAGS} ${_iconv_link_flag}")
  ENDFOREACH ()
ELSE (_ICONV_FOUND)
  SET (_ICONV_LINK_FLAGS)
  SET (_ICONV_LDFLAGS)
ENDIF (_ICONV_FOUND)

SET (ICONV_LINK_FLAGS ${_ICONV_LINK_FLAGS} CACHE STRING "Linker flags when linking against Iconv (list)")
SET (ICONV_LDFLAGS "${_ICONV_LDFLAGS}" CACHE STRING "Linker flags when linking against Iconv")

IF (_ICONV_FOUND)
  MESSAGE(STATUS "-----------------------------------------")
  MESSAGE(STATUS "Setup Iconv:")
  MESSAGE(STATUS "")
  MESSAGE(STATUS "              INCLUDE_DIR: ${ICONV_INCLUDE_DIR}")
  MESSAGE(STATUS "              LINK_FLAGS : ${ICONV_LINK_FLAGS}")
  MESSAGE(STATUS "                 LDFLAGS : ${ICONV_LDFLAGS}")
  MESSAGE(STATUS " SECOND_ARGUMENT_IS_CONST: ${ICONV_SECOND_ARGUMENT_IS_CONST}")
  MESSAGE(STATUS "-----------------------------------------")
ENDIF()

MARK_AS_ADVANCED(
  ICONV_FOUND
  ICONV_INCLUDE_DIR
  ICONV_LINK_FLAGS
  ICONV_LDFLAGS
  ICONV_SECOND_ARGUMENT_IS_CONST
  )
