# Module for locating lua534, based on ICU module.
#
# Cutomizable variables:
#   LUA534_ROOT_DIR
#     This variable points to the lua534 root directory. On Windows the
#     library location typically will have to be provided explicitly using the
#     -D command-line option. Alternatively, an environment variable can be set.
#
# Read-Only variables:
#   LUA534_FOUND
#     Indicates whether the library has been found.
#
#   LUA534_INCLUDE_DIRS
#     Points to the lua534 include directory.
#
#   LUA534_LIBRARIES
#     Points to the lua534 libraries that should be passed to
#     target_link_libraries in dynamic mode.
#
#   LUA534_STATIC_LIBRARIES
#     Points to the lua534 libraries static that should be passed to
#     target_link_libraries in static mode.
#
#   LUA534_LINK_FLAGS
#     Linker flags when building linking against lua534. Defaults to "liblua534". Take care, this is a list.
#
#   LUA534_STATIC_LINK_FLAGS
#     Linker flags when building linking against static lua534. Defaults to "liblua534_static". Take care, this is a list.
#
#   LUA534_LDFLAGS
#     Stringified version of LUA534_LINK_FLAGS
#
#   LUA534_STATIC_LDFLAGS
#     Stringified version of LUA534_STATIC_LINK_FLAGS
#
INCLUDE (CMakeParseArguments)
INCLUDE (FindPackageHandleStandardArgs)

SET (_PF86 "ProgramFiles(x86)")
SET (_LUA534_POSSIBLE_DIRS
  ${LUA534_ROOT_DIR}
  "$ENV{LUA534_ROOT_DIR}"
  "C:/lua534"
  "$ENV{PROGRAMFILES}/lua534"
  "$ENV{${_PF86}}/lua534")

SET (_LUA534_POSSIBLE_INCLUDE_SUFFIXES include)

IF (CMAKE_SIZEOF_VOID_P EQUAL 8)
  SET (_LUA534_POSSIBLE_LIB_SUFFIXES lib64)
  SET (_LUA534_POSSIBLE_BIN_SUFFIXES bin64)

  IF (NOT WIN32)
    LIST (APPEND _LUA534_POSSIBLE_LIB_SUFFIXES lib)
    LIST (APPEND _LUA534_POSSIBLE_BIN_SUFFIXES bin)
  ENDIF (NOT WIN32)
ELSE (CMAKE_SIZEOF_VOID_P EQUAL 8)
  SET (_LUA534_POSSIBLE_LIB_SUFFIXES lib)
  SET (_LUA534_POSSIBLE_BIN_SUFFIXES bin)
ENDIF (CMAKE_SIZEOF_VOID_P EQUAL 8)

FIND_PATH (LUA534_ROOT_DIR
  NAMES include/lua534.h
  PATHS ${_LUA534_POSSIBLE_DIRS}
  DOC "lua534 root directory")

IF (LUA534_ROOT_DIR)
  # Re-use the previous path:
  FIND_PATH (LUA534_INCLUDE_DIR
    NAMES lua534.h
    PATHS ${LUA534_ROOT_DIR}
    PATH_SUFFIXES ${_LUA534_POSSIBLE_INCLUDE_SUFFIXES}
    DOC "lua534 include directory"
    # NO_DEFAULT_PATH
    )
ELSE (LUA534_ROOT_DIR)
  # Use default path search
  FIND_PATH (LUA534_INCLUDE_DIR
    NAMES lua534.h
    DOC "lua534 include directory"
    )
ENDIF (LUA534_ROOT_DIR)

IF (NOT LUA534_FIND_COMPONENTS)
  SET (LUA534_FIND_COMPONENTS lua534)
ENDIF (NOT LUA534_FIND_COMPONENTS)

IF (LUA534_INCLUDE_DIR)
  # Loop over each components
  FOREACH (_LUA534_COMPONENT ${LUA534_FIND_COMPONENTS})
    SET (_LUA534_COMPONENT_BASE ${_LUA534_COMPONENT})
    SET (_LUA534_COMPONENT_POSSIBLE_DEBUG_NAMES ${_LUA534_COMPONENT_BASE}d)
    SET (_LUA534_COMPONENT_POSSIBLE_RELEASE_NAMES ${_LUA534_COMPONENT_BASE})

    SET (_LUA534_STATIC_COMPONENT_BASE "${_LUA534_COMPONENT}_static")
    SET (_LUA534_STATIC_COMPONENT_POSSIBLE_DEBUG_NAMES ${_LUA534_STATIC_COMPONENT_BASE}d)
    SET (_LUA534_STATIC_COMPONENT_POSSIBLE_RELEASE_NAMES ${_LUA534_STATIC_COMPONENT_BASE})

    STRING (TOUPPER ${_LUA534_COMPONENT} _LUA534_COMPONENT_UPPER)
    SET (_LUA534_LIBRARY_BASE LUA534_${_LUA534_COMPONENT_UPPER}_LIBRARY)
    SET (_LUA534_STATIC_LIBRARY_BASE LUA534_STATIC_${_LUA534_COMPONENT_UPPER}_LIBRARY)

    IF (LUA534_ROOT_DIR)
      FIND_LIBRARY (${_LUA534_LIBRARY_BASE}_DEBUG
	NAMES ${_LUA534_COMPONENT_POSSIBLE_DEBUG_NAMES}
	PATHS ${LUA534_ROOT_DIR} PATH_SUFFIXES ${_LUA534_POSSIBLE_LIB_SUFFIXES}
	# NO_DEFAULT_PATH
	)
      FIND_LIBRARY (${_LUA534_STATIC_LIBRARY_BASE}_DEBUG
	NAMES ${_LUA534_STATIC_COMPONENT_POSSIBLE_DEBUG_NAMES}
	PATHS ${LUA534_ROOT_DIR} PATH_SUFFIXES ${_LUA534_POSSIBLE_LIB_SUFFIXES}
	# NO_DEFAULT_PATH
	)
    ELSE (LUA534_ROOT_DIR)
      FIND_LIBRARY (${_LUA534_LIBRARY_BASE}_DEBUG
	NAMES ${_LUA534_COMPONENT_POSSIBLE_DEBUG_NAMES}
	PATH_SUFFIXES ${_LUA534_POSSIBLE_LIB_SUFFIXES}
	)
      FIND_LIBRARY (${_LUA534_STATIC_LIBRARY_BASE}_DEBUG
	NAMES ${_LUA534_COMPONENT_STATIC_POSSIBLE_DEBUG_NAMES}
	PATH_SUFFIXES ${_LUA534_POSSIBLE_LIB_SUFFIXES}
	)
    ENDIF (LUA534_ROOT_DIR)

    IF (LUA534_ROOT_DIR)
      FIND_LIBRARY (${_LUA534_LIBRARY_BASE}_RELEASE
	NAMES ${_LUA534_COMPONENT_POSSIBLE_RELEASE_NAMES}
	PATHS ${LUA534_ROOT_DIR} PATH_SUFFIXES ${_LUA534_POSSIBLE_LIB_SUFFIXES}
	# NO_DEFAULT_PATH
	)
      FIND_LIBRARY (${_LUA534_STATIC_LIBRARY_BASE}_RELEASE
	NAMES ${_LUA534_STATIC_COMPONENT_POSSIBLE_RELEASE_NAMES}
	PATHS ${LUA534_ROOT_DIR} PATH_SUFFIXES ${_LUA534_POSSIBLE_LIB_SUFFIXES}
	# NO_DEFAULT_PATH
	)
    ELSE (ICU_ROOT_DIR)
      FIND_LIBRARY (${_LUA534_LIBRARY_BASE}_RELEASE
	NAMES ${_LUA534_COMPONENT_POSSIBLE_RELEASE_NAMES}
	PATH_SUFFIXES ${_LUA534_POSSIBLE_LIB_SUFFIXES}
	)
      FIND_LIBRARY (${_LUA534_STATIC_LIBRARY_BASE}_RELEASE
	NAMES ${_LUA534_STATIC_COMPONENT_POSSIBLE_RELEASE_NAMES}
	PATH_SUFFIXES ${_LUA534_POSSIBLE_LIB_SUFFIXES}
	)
    ENDIF (LUA534_ROOT_DIR)

    SET (LUA534_${_LUA534_COMPONENT_UPPER}_FOUND TRUE)

    # Debug and release
    IF (${_LUA534_LIBRARY_BASE}_DEBUG AND ${_LUA534_LIBRARY_BASE}_RELEASE)
      SET (${_LUA534_LIBRARY_BASE}
        debug ${${_LUA534_LIBRARY_BASE}_DEBUG}
        optimized ${${_LUA534_LIBRARY_BASE}_RELEASE})
      # Debug only
    ELSEIF (${_LUA534_LIBRARY_BASE}_DEBUG)
      SET (${_LUA534_LIBRARY_BASE} ${${_LUA534_LIBRARY_BASE}_DEBUG})
      # Release only
    ELSEIF (${_LUA534_LIBRARY_BASE}_RELEASE)
      SET (${_LUA534_LIBRARY_BASE} ${${_LUA534_LIBRARY_BASE}_RELEASE})
    ELSE (${_LUA534_LIBRARY_BASE}_DEBUG AND ${_LUA534_LIBRARY_BASE}_RELEASE)
      # Component missing: record it for a later report
      LIST (APPEND _LUA534_MISSING_COMPONENTS ${_LUA534_COMPONENT})
      SET (LUA534_${__COMPONENT_UPPER}_FOUND FALSE)
    ENDIF (${_LUA534_LIBRARY_BASE}_DEBUG AND ${_LUA534_LIBRARY_BASE}_RELEASE)

    IF (${_LUA534_STATIC_LIBRARY_BASE}_DEBUG AND ${_LUA534_STATIC_LIBRARY_BASE}_RELEASE)
      SET (${_LUA534_STATIC_LIBRARY_BASE}
        debug ${${_LUA534_STATIC_LIBRARY_BASE}_DEBUG}
        optimized ${${_LUA534_STATIC_LIBRARY_BASE}_RELEASE})
      # Debug only
    ELSEIF (${_LUA534_STATIC_LIBRARY_BASE}_DEBUG)
      SET (${_LUA534_STATIC_LIBRARY_BASE} ${${_LUA534_STATIC_LIBRARY_BASE}_DEBUG})
      # Release only
    ELSEIF (${_LUA534_STATIC_LIBRARY_BASE}_RELEASE)
      SET (${_LUA534_STATIC_LIBRARY_BASE} ${${_LUA534_STATIC_LIBRARY_BASE}_RELEASE})
    ELSE (${_LUA534_STATIC_LIBRARY_BASE}_DEBUG AND ${_LUA534_STATIC_LIBRARY_BASE}_RELEASE)
      # Component missing: record it for a later report
      LIST (APPEND _LUA534_STATIC_MISSING_COMPONENTS ${_LUA534_COMPONENT})
      SET (LUA534_STATIC_${__COMPONENT_UPPER}_FOUND FALSE)
    ENDIF (${_LUA534_STATIC_LIBRARY_BASE}_DEBUG AND ${_LUA534_STATIC_LIBRARY_BASE}_RELEASE)

    MARK_AS_ADVANCED (${_LUA534_LIBRARY_BASE}_DEBUG ${_LUA534_LIBRARY_BASE}_RELEASE)
    MARK_AS_ADVANCED (${_LUA534_STATIC_LIBRARY_BASE}_DEBUG ${_LUA534_STATIC_LIBRARY_BASE}_RELEASE)

    # Make sure only libraries that have been actually found are registered
    IF (${_LUA534_LIBRARY_BASE})
      LIST (APPEND _LUA534_LIBRARIES ${${_LUA534_LIBRARY_BASE}})
    ENDIF (${_LUA534_LIBRARY_BASE})

    IF (${_LUA534_STATIC_LIBRARY_BASE})
      LIST (APPEND _LUA534_STATIC_LIBRARIES ${${_LUA534_STATIC_LIBRARY_BASE}})
    ENDIF (${_LUA534_STATIC_LIBRARY_BASE})

  ENDFOREACH (_LUA534_COMPONENT)

  IF (NOT DEFINED _LUA534_MISSING_COMPONENTS AND NOT DEFINED _LUA534_STATIC_MISSING_COMPONENTS)
    # Success: all components were found
    SET (LUA534_INCLUDE_DIRS "${LUA534_INCLUDE_DIR}")
    SET (LUA534_LIBRARIES ${_LUA534_LIBRARIES})
    SET (LUA534_STATIC_LIBRARIES ${_LUA534_STATIC_LIBRARIES} ${CMAKE_DL_LIBS})
  ELSE ()
    MESSAGE (STATUS "Several LUA534 components were not found:")

    # Display missing components indented, each on a separate line
    FOREACH (_LUA534_MISSING_COMPONENT ${_LUA534_MISSING_COMPONENTS})
      MESSAGE (STATUS "  " ${_LUA534_MISSING_COMPONENT})
    ENDFOREACH ()
    FOREACH (_LUA534_STATIC_MISSING_COMPONENT ${_LUA534_STATIC_MISSING_COMPONENTS})
      MESSAGE (STATUS "  " ${_LUA534_STATIC_MISSING_COMPONENT})
    ENDFOREACH ()
  ENDIF ()

  #
  # Simulate hopefully correct flags based on heuristic discovery
  #
  IF (NOT _LUA534_C_FLAGS_SHARED)
    SET (_LUA534_C_FLAGS_SHARED "${CMAKE_SHARED_LIBRARY_C_FLAGS}")
  ENDIF ()

  IF (NOT _LUA534_CXX_FLAGS_SHARED)
    SET (_LUA534_CXX_FLAGS_SHARED "${CMAKE_SHARED_LIBRARY_CXX_FLAGS}")
  ENDIF ()

  IF (NOT _LUA534_LINK_FLAGS)
    SET (_LUA534_LINK_FLAGS ${LUA534_LIBRARIES})
  ENDIF ()

  IF (NOT _LUA534_STATIC_LINK_FLAGS)
    SET (_LUA534_STATIC_LINK_FLAGS ${LUA534_STATIC_LIBRARIES})
  ENDIF ()

ENDIF (LUA534_INCLUDE_DIR)

SET (_LUA534_LDFLAGS " ")
FOREACH (_lua534_link_flag ${_LUA534_LINK_FLAGS})
  SET (_LUA534_LDFLAGS "${_LUA534_LDFLAGS} ${_lua534_link_flag}")
ENDFOREACH ()

SET (_LUA534_STATIC_LDFLAGS " ")
FOREACH (_lua534_static_link_flag ${_LUA534_STATIC_LINK_FLAGS})
  SET (_LUA534_STATIC_LDFLAGS "${_LUA534_STATIC_LDFLAGS} ${_lua534_static_link_flag}")
ENDFOREACH ()

MARK_AS_ADVANCED (LUA534_ROOT_DIR LUA534_INCLUDE_DIR)

FIND_PACKAGE_HANDLE_STANDARD_ARGS (LUA534
  REQUIRED_VARS
  LUA534_INCLUDE_DIR
  LUA534_LIBRARIES)

IF (_LUA534_LINK_FLAGS AND _LUA534_STATIC_LINK_FLAGS)
  SET (LUA534_FOUND 1 CACHE STRING "LUA534 is found")
ENDIF ()

SET (LUA534_C_FLAGS_SHARED    "${_LUA534_C_FLAGS_SHARED}"    CACHE STRING "C flags when compiling against shared LUA534")
SET (LUA534_CXX_FLAGS_SHARED  "${_LUA534_CXX_FLAGS_SHARED}"  CACHE STRING "C flags when compiling against shared LUA534")
SET (LUA534_LINK_FLAGS        "${_LUA534_LINK_FLAGS}"        CACHE STRING "Linker flags when linking against LUA534")
SET (LUA534_LDFLAGS           "${_LUA534_LDFLAGS}"           CACHE STRING "Stringified version of LUA534_LINK_FLAGS")
SET (LUA534_STATIC_LINK_FLAGS "${_LUA534_STATIC_LINK_FLAGS}" CACHE STRING "Linker flags when linking against static LUA534")
SET (LUA534_STATIC_LDFLAGS    "${_LUA534_STATIC_LDFLAGS}"    CACHE STRING "Stringified version of LUA534_STATIC_LINK_FLAGS")

IF(LUA534_FOUND)
  MESSAGE(STATUS "-----------------------------------------")
  MESSAGE(STATUS "Setup LUA534:")
  MESSAGE(STATUS "")
  MESSAGE(STATUS "           ROOT_DIR: ${LUA534_ROOT_DIR}")
  MESSAGE(STATUS "     C_FLAGS_SHARED: ${LUA534_C_FLAGS_SHARED}")
  MESSAGE(STATUS "   CXX_FLAGS_SHARED: ${LUA534_CXX_FLAGS_SHARED}")
  MESSAGE(STATUS "        INCLUDE_DIR: ${LUA534_INCLUDE_DIR}")
  MESSAGE(STATUS "          LIBRARIES: ${LUA534_LIBRARIES}")
  MESSAGE(STATUS "   STATIC LIBRARIES: ${LUA534_STATIC_LIBRARIES}")
  MESSAGE(STATUS "         LINK_FLAGS: ${LUA534_LINK_FLAGS}")
  MESSAGE(STATUS "  STATIC LINK_FLAGS: ${LUA534_STATIC_LINK_FLAGS}")
  MESSAGE(STATUS "            LDFLAGS: ${LUA534_LDFLAGS}")
  MESSAGE(STATUS "     STATIC LDFLAGS: ${LUA534_STATIC_LDFLAGS}")
  MESSAGE(STATUS "-----------------------------------------")
ENDIF()

MARK_AS_ADVANCED (
  LUA534_FOUND
  LUA534_C_FLAGS_SHARED
  LUA534_CXX_FLAGS_SHARED
  LUA534_LINK_FLAGS
  LUA534_LDFLAGS
  LUA534_STATIC_LINK_FLAGS
  LUA534_STATIC_LDFLAGS
  )
