MACRO (MYPACKAGECHECKCOMMONFEATURES)
  FINDEBCDIC()
  FINDINLINE()
  FINDFORCEINLINE()
  FINDVACOPY()
  FINDVSNPRINTF()
  FINDFILENO()
  FINDLOCALTIME_R()
  FINDWRITE()
  FINDLOG2()
  FINDLOG2F()
  FINDLOG2L()
  FINDCHAR_BIT()
  FINDSTRTOLD()
  FINDSTRTOD()
  FINDSTRTOF()
  FINDHUGE_VAL()
  FINDHUGE_VALF()
  FINDHUGE_VALL()
  FINDINFINITY()
  FINDNAN()
  FINDISINF()
  FINDISNAN()
  FINDSTRTOLL()
  FINDSTRTOULL()
  FINDFPCLASSIFY()
  FINDCONST()
  FINDC99MODIFIERS()
  FINDRESTRICT()
  FIND__BUILTIN_EXPECT()
  FINDSIGNBIT()
  FINDCOPYSIGN()
  FINDCOPYSIGNF()
  FINDCOPYSIGNL()
  FIND__GNUC__()
  IF (C___GNUC__)
    FOREACH (_attribute alias aligned alloc_size always_inline artificial cold const constructor_priority constructor deprecated destructor dllexport dllimport error externally_visible fallthrough flatten format gnu_format format_arg gnu_inline hot ifunc leaf malloc noclone noinline nonnull noreturn nothrow optimize pure sentinel sentinel_position returns_nonnull unused used visibility warning warn_unused_result weak weakref)
      FINDGCCFUNCATTRIBUTE(${_attribute})
    ENDFOREACH ()
    ENDIF ()
ENDMACRO()
