#SET (BUILD_SHARED_LIBS ON CACHE BOOL "BUILD_SHARED_LIBS" FORCE)
SET (BUILD_CLAR OFF CACHE BOOL "BUILD_CLAR" FORCE)
SET (THREADSAFE ON CACHE BOOL "THREADSAFE" FORCE)
SET (CMAKE_SYSTEM_NAME Windows CACHE STRING "CMAKE_SYSTEM_NAME" FORCE)
SET (CMAKE_C_COMPILER /usr/bin/i686-w64-mingw32-gcc CACHE PATH "CMAKE_C_COMPILER" FORCE)
SET (CMAKE_CXX_COMPILER /usr/bin/i686-w64-mingw32-g++ CACHE PATH "CMAKE_CXX_COMPILER" FORCE)
SET (CMAKE_RC_COMPILER /usr/bin/i686-w64-mingw32-windres CACHE PATH "CMAKE_RC_COMPILER" FORCE)
SET (DLLTOOL /usr/bin/i686-w64-mingw32-dlltool CACHE PATH "DLLTOOL" FORCE)
SET (CMAKE_FIND_ROOT_PATH /usr/i686-w64-mingw32 CACHE PATH "CMAKE_FIND_ROOT_PATH" FORCE)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY CACHE STRING "CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY" FORCE)
SET (TARGET_TEST_CMAKE_COMMAND "testbin/WindowsTest.sh" CACHE STRING "TARGET_TEST_CMAKE_COMMAND" FORCE)
SET (WIN32 ON CACHE BOOL "WIN32" FORCE)
#
# Force ICU search failure - not very elegant but will always work
#
SET (ICU_ROOT_DIR "" CACHE STRING "ICU_ROOT_DIR" FORCE)
SET (ICU_CONFIG_EXECUTABLE "" CACHE STRING "ICU_CONFIG_EXECUTABLE CACHE" FORCE)
#
# From TryRunResults.cmake
#
SET (ICONV_CAN_TRANSLIT_EXITCODE "0" CACHE STRING "ICONV_CAN_TRANSLIT_EXITCODE" FORCE)
SET (ICONV_CAN_IGNORE_EXITCODE "0" CACHE STRING "ICONV_CAN_IGNORE_EXITCODE" FORCE)
